'a) vòng lặp bắt đầu kết thúc tại 5'
'b) vòng lặp bắt đầu bằng 5 và kết thúc tại 10'
'c) vòng lặp bắt đầu bằng 5 và kết thúc tại 20, bước nhảy 3'
'd) vòng lặp bắt đầu bằng 20 và kết thúc tại 5, bước nhảy -1'
'e) vòng lặp bắt đầu bằng 20 và kết thúc tại 5, bước nhảy -3'
'f) vòng lặp bắt đầu bằng 10 và kết thúc tại 5'
'g) Rỗng'
'h) vòng lặp bắt đầu bằng 10 và kết thức băng 101, bước nhảy 10'
'i) vòng lặp bắt đầu bằng 10 và kết thúc bằng -1, bước nhảy là -1'
'j) vòng lặp bắt đầu bằng -3 và kết thúc tại 4'
'k) vòng lặp bắt đầu bằng 0 và kết thúc tại 10, bước nhảy 1'    